<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/1/7
 * Time: 21:20
 */

namespace common\components\widget;

use common\assets\LayuiAsset;
use yii\helpers\Html;
use yii\widgets\ActiveField;
class DateOneSelectField extends ActiveField
{
    public $dateConfig=[];
    public $dateformate='Y-m-d H:i:s';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if(empty($this->dateConfig)){
            $this->dateConfig=[
                'elem'=>'',
                'type'=>'datetime',
                'calendar'=>'true',
                'max'=>date('Y-m-d H:i:s',strtotime('+1 hour')),
                'btns'=>['clear', 'confirm'],
            ];
        }
    }

    /**
     * @param array $options
     * @return $this
     */
    public function textInput($options = [])
    {
        parent::textInput($options);
        $str=$this->parts['{input}'];

        if(preg_match('/input.*value="(.*)"/',$str,$match)){
            if($match[1]==false){
                $value='';
            }else{
                $value=date($this->dateformate,$match[1]);
            }

            $this->parts['{input}']=preg_replace('/(input.*value=")(.*)(")/','${1}'.$value.'${3}',$str);
        }

        $this->renderJs();
        return $this;
    }

    public function renderJs(){
        $this->dateConfig['elem']='#'.$this->getInputId();
        if(empty($this->dateConfig['closeStop'])){
            $this->dateConfig['closeStop']=$this->dateConfig['elem'];
        }
        if(empty($this->dateConfig['done'])){
            $this->dateConfig['done']='function(value, date, endDate){ $(this.elem).val(value); $(this.elem).change();}';
        }

        $config=json_encode($this->dateConfig);
        $content=<<<SCRIPT
           laydate.render({$config});
SCRIPT;
        LayuiUse::widget(['content'=>$content,'module'=>['laydate']]);

    }

}