<?php
namespace lbmzorx\components\grid;

use Yii;
use yii\helpers\Url;
use yii\helpers\Html;
use yii\helpers\StringHelper;

/**
 * @inheritdoc
 */
class SortColumn extends \yii\grid\DataColumn
{
    public $sortInputOptions=[];
    public $attribute='sort';
    public $griViewKey=0;
    public static $renderSortJsCount=[];
    public $primaryKey='id';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if(empty($this->sortInputOptions['url'])){
            $this->sortInputOptions['url']=['sort'];
        }
        if(empty($this->sortInputOptions['class'])){
            $this->sortInputOptions['class']='form-control';
        }
    }

    protected function renderDataCellContent($model , $key , $index)
    {
        $class_change=StringHelper::basename(get_class($model)).'_'.$this->attribute.'-sort-change';
        $this->sortInputOptions['class']=(isset($this->sortInputOptions['class'])?$this->sortInputOptions['class'].' ':'').$class_change;

        if(empty($this->sortInputOptions['data-'.$this->primaryKey])){
            $this->sortInputOptions['data-'.$this->primaryKey]=$model->{$this->primaryKey};
        }

        $url=Url::to($this->sortInputOptions['url']);
        if(empty(static::$renderSortJsCount[$this->attribute])){
            $js=<<<str
$('.{$class_change}').blur(function(){
    var sort=$(this).val(),id=$(this).attr('data-{$this->primaryKey}'),name=$(this).attr('name'); 
    var data={{$this->primaryKey}:id};
    data[name]=sort;
    var load=layer.load();
    $.ajax({
        url:'{$url}',
        type:'post',
        data:data,
        success:function(res){
            layer.close(load);
            if(res.status){
                layer.msg(res.msg);
                $.pjax.reload("#w{$this->griViewKey}");
            }else{
                layer.alert(res.msg);
            }
        },
        error:function(res){
            console.log(res);
            layer.alert(res.responseText);
            layer.close(load);
        }
    });
});
str;
            \yii::$app->getView()->registerJs($js);
            static::$renderSortJsCount[$this->attribute]=1;
        }


        return Html::input('number',$this->attribute,parent::renderDataCellContent($model , $key , $index),$this->sortInputOptions); // TODO: Change the autogenerated stub
    }

}