<?php
/**
 * Created by Administrator.
 * Date: 2018/6/3 18:13
 * github: https://github.com/lbmzorx
 */
namespace lbmzorx\components\action;

use yii;
use yii\base\Action;
use lbmzorx\components\helper\ModelHelper;

/**
 * Class FormAction
 *
 * this action will be common action for model, validate data and deal with id which data is posted from user.
 * if there is form
 * example : in controller
 * public function actions(){
 * return [
 * 'activate'=>[
        'class'=>FormAction::className(),
        'modelClass'=>ActivateForm::className(),
        'verifyMethod'=>'sendEmail',
        'successMsg'=>\yii::t('app','Congratulations! We have send an email to you account, please click it and activate you account'),
        'isErrorMsg'=>true,
        'successRedirectvView'=>'/site/login',
 * ],
 * ];
 * }
 * @package lbmzorx\components\action
 */
class FormAction extends Action
{
    /**
     * model class
     * @var
     */
    public $modelClass;
    /**
     * after validate post data, next method to execute
     * @var
     */
    public $verifyMethod;

    /**
     * data to render view
     * @var array|\Closure
     */
    public $data;

    /**
     * different scenario has different rules to validate data
     * @var
     */
    public $scenario;

    /**
     * if success , msg to show
     * @var string
     */
    public $successMsg='';

    /**
     * if error , msg to from model
     * @var string
     */
    public $isErrorMsg=true;

    /**
     * if error , msg to show. when $isErrorMsg is false
     * @var string
     */
    public $errorMsg='';

    /**
     * if success view redirect to.
     * @var string
     */
    public $successRedirectvView;
    /** @var $viewFile string 模板路径，默认为action id  */
    public $viewFile = null;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if ($this->viewFile==null){
            $this->viewFile = $this->id;
        }
    }

    public function run()
    {
        /**
         * @var $model \yii\base\Model
         */
        $model = new $this->modelClass;
        if($this->scenario){
            $model->setScenario($this->scenario);
        }

        $request=yii::$app->getRequest();
        if ($request->getIsPost()) {
            if ($model->load($request->post()) && $model->validate()) {
                $status=true;
                if(method_exists($model,$this->verifyMethod)){
                    if(! $model->{$this->verifyMethod}()){
                        $status=false;
                    }
                }
            } else {
                $status=false;
            }
            $msg='';
            if($status==true){
                if($this->successMsg){
                    $msg=$this->successMsg;
                }
            }else{
                if($this->isErrorMsg){
                    $msg=ModelHelper::getErrorAsString($model,$model->getErrors());
                }else{
                    $msg=$this->errorMsg;
                }
            }

            Yii::$app->getSession()->setFlash($status?'success':'error',$msg);
            if($request->isAjax){
                return ['status'=>$status,'msg'=>$msg];
            }else{
                if($this->successRedirectvView){
                    return $this->controller->redirect($this->successRedirectvView);
                }
            }
        }

        $data = [
            'model' => $model,
        ];
        if( is_array($this->data) ){
            $data = array_merge($data, $this->data);
        }elseif ($this->data instanceof \Closure){
            $data = call_user_func_array($this->data, [$model, $this]);
        }
        return $this->controller->render($this->viewFile,$data);
    }
}