<?php
/**
 * Created  WithOneUser.php.
 * Date: 2018/4/30 18:07
 * Emain: lbmzorx@163.com
 * Github: https://github.com/lbmzorx
 */

namespace lbmzorx\components\behaviors;

use Yii;
use common\models\data\User;
use yii\base\Behavior;
use yii\base\InvalidParamException;

class WithOneUser extends Behavior
{
    public  $userClass;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if($this->userClass=='' || !class_exists($this->userClass)){
            throw new InvalidParamException(Yii::t('lbmzorx','Invalid User Class'));
        }
    }

    public function getBaseUser(){
        return $this->owner->hasOne(User::className(),['id'=>'user_id'])->select('id,name,head')->asArray();
    }
}