<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/1/7
 * Time: 21:20
 */
namespace lbmzorx\components\widget;

use yii;
use yii\helpers\StringHelper;
use yii\helpers\Html;
use yii\widgets\ActiveField;
class DoubleSelect extends ActiveField
{
    public $groupOneName='New Input';
    public $groupTwoName='Build From Select';


    public $inputSelectOptions=[];
    public $itemsSelect=[];

    public $template="{label}\n{inputSelect}\n{input}\n{hint}\n{hiddenDropList}\n{error}";

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if(empty($this->inputSelectOptions['style'])){
            $this->inputSelectOptions['style']='float:right';
        }
    }

    public function render($content = null)
    {
        if ($content === null) {
            if (!isset($this->parts['{inputSelect}'])) {
                $this->inputSelect();
            }
        }
        return parent::render($content); // TODO: Change the autogenerated stub
    }

    public function inputSelect($options=[]){
        $options=array_merge($this->inputSelectOptions,$options);
        $item=$this->itemsSelect;
        $this->parts['{inputSelect}']=Html::radioList($this->attribute.'-input-select',0,$item,$options);
        return $this;
    }

    public function hiddenDropList($items, $options = []){
        $options= array_merge($options, ['style'=>'display:none']);
        $options = array_merge($this->inputOptions, $options);
        $this->addAriaAttributes($options);
        $this->adjustLabelFor($options);
        if(empty($options['id'])){
            $id=Html::getInputId($this->model,$this->attribute);
            $options['id']=$id.'-hidden';
        }
        $this->parts['{hiddenDropList}']=Html::dropDownList(StringHelper::basename(get_class($this->model)).'_'.$this->attribute.'-hidden',null,$items, $options);
        return $this;
    }

}